version: '3.8'
services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /opt/GestionaleBar/bar.db:/app/Database/bar.db
      - /opt/GestionaleBar/exports:/app/exports